insert into artist (Artist_Id,Name) values (1,'AC/DC');
insert into artist (Artist_Id,Name) values (2,'Accept');
insert into artist (Artist_Id,Name) values (3,'Aerosmith');
insert into artist (Artist_Id,Name) values (4,'Alanis Morisette');
insert into artist (Artist_Id,Name) values (5,'Alice In Chains');
insert into artist (Artist_Id,Name) values (6,'Carlos Jobim');
insert into artist (Artist_Id,Name) values (7,'Apocalyptica');
insert into artist (Artist_Id,Name) values (8,'Audioslave');
insert into artist (Artist_Id,Name) values (9,'BackBeat');
insert into artist (Artist_Id,Name) values (10,'Samurai');